package com.nutrehogar.sistemacontable.ui.service;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.nutrehogar.sistemacontable.HibernateUtil;
import com.nutrehogar.sistemacontable.config.PasswordHasher;
import com.nutrehogar.sistemacontable.config.Theme;
import com.nutrehogar.sistemacontable.exception.ApplicationException;
import com.nutrehogar.sistemacontable.model.User;
import com.nutrehogar.sistemacontable.query.UserQuery_;
import com.nutrehogar.sistemacontable.service.worker.FromTransactionWorker;
import com.nutrehogar.sistemacontable.ui_2.builder.UserListCellRenderer;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.*;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@Slf4j
public class AuthView extends JDialog {
    @NotNull
    private static final FlatSVGIcon icon = new FlatSVGIcon("svgs/key.svg");

    @NotNull
    private final DefaultListModel<User> userListModel;

    @NotNull
    private final User adminUser;

    @Getter
    private User autenicateUser;

    public AuthView(@NotNull Frame owner, boolean modal, @NotNull User adminUser) {
        super(owner, modal);
        this.adminUser = adminUser;
        this.userListModel = new DefaultListModel<>();
        initComponents();
        new FromTransactionWorker<>(
                session -> new UserQuery_(session).findAllEnables(),
                users -> {
                    userListModel.removeAllElements();
                    userListModel.addAll(users);
                    userListModel.addElement(adminUser);
                    if (!userListModel.isEmpty()) {
                        lstUser.setSelectedIndex(0);
                        btnOk.setEnabled(true);
                    }
                },
                this::showError
        ).execute();

        var cancelName = "cancel";

        getRootPane().setBackground(getBackground());

        getRootPane()
                .getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);

        getRootPane()
                .getActionMap()
                .put(cancelName, new AbstractAction() {
                    public void actionPerformed(ActionEvent e) {
                        closeDialog(null);
                    }
                });

        BtnCancel.addActionListener(_ -> {
            log.info("System.exit");
            System.exit(0);
        });

        lstUser.addListSelectionListener(_-> txtPing.grabFocus());
        txtPing.addActionListener(_->btnOk.doClick());


        btnOk.addActionListener(_ -> {
            if (userListModel.isEmpty()) return;

            var selectedUser = lstUser.getSelectedValue();

            if(selectedUser == null) return;

            var insertPass = String.valueOf(txtPing.getPassword());

            if(selectedUser.isAdmin()
                    && selectedUser.getUsername().equals(adminUser.getUsername())) {
                if (!insertPass.equals(adminUser.getPassword())) {
                    showError(new ApplicationException("Contraseña Incorrecta."));
                    return;
                }
                autenicateUser = adminUser;
                setVisible(false);
                dispose();
                IO.println("bien termino-admin");
                return;

            }

            if(!PasswordHasher.verifyPassword(insertPass, selectedUser.getPassword())) {
                showError(new ApplicationException("Contraseña Incorrecta."));
                return;
            }

            IO.println("bien termino");

            autenicateUser = selectedUser;
            setVisible(false);
            dispose();
        });

    }
    void showError(@Nullable ApplicationException cause) {
        JOptionPane.showMessageDialog(this, cause.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.nutrehogar.sistemacontable.ui_2.component.Background();
        btnOk = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        scrollPanel1 = new com.nutrehogar.sistemacontable.ui_2.component.ScrollPanel();
        lstUser = new javax.swing.JList<>();
        lblTitle = new javax.swing.JLabel();
        txtPing = new javax.swing.JPasswordField();
        lblPing = new javax.swing.JLabel();

        setTitle("Ingrese su PING");
        setBackground(new java.awt.Color(239, 248, 255));
        setIconImage(Theme.SVGs.KEY.getIcon().getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        background1.setColor1(new java.awt.Color(229, 243, 255));
        background1.setColor2(new java.awt.Color(239, 248, 255));
        background1.setColor3(new java.awt.Color(255, 255, 255));
        background1.setColor4(new java.awt.Color(255, 255, 255));
        background1.setFundType(com.nutrehogar.sistemacontable.ui_2.component.Background.FundType.LINEAL);

        btnOk.setText("OK");

        BtnCancel.setText("Cancelar");

        lstUser.setModel(userListModel);
        lstUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstUser.setCellRenderer(new UserListCellRenderer());
        lstUser.setOpaque(false);
        scrollPanel1.setViewportView(lstUser);

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Usuarios");

        lblPing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPing.setIcon(Theme.SVGs.KEY.getIcon());
        lblPing.setText("Ping:");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCancel))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(lblPing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPing)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPing))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnOk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
        System.exit(0);
    }// GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private com.nutrehogar.sistemacontable.ui_2.component.Background background1;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblPing;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<User> lstUser;
    private com.nutrehogar.sistemacontable.ui_2.component.ScrollPanel scrollPanel1;
    private javax.swing.JPasswordField txtPing;
    // End of variables declaration//GEN-END:variables

}
