/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui_2.component;

import com.nutrehogar.sistemacontable.Main;
import com.nutrehogar.sistemacontable.config.LabelBuilder;
import com.nutrehogar.sistemacontable.config.Util;
import com.nutrehogar.sistemacontable.ui.View;
import org.jetbrains.annotations.NotNull;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.nio.file.Path;
import javax.swing.*;

/**
 *
 * @author Calci
 */
public class ReportResponseDialog extends javax.swing.JDialog {
    enum Option {
        /**
         * A return status code - returned if Cancel button has been pressed
         */
        CANCEL,
        /**
         * A return status code - returned if OK button has been pressed
         */
        PDF,
        DIR
    }
    private final @NotNull Path path;
    private final @NotNull View parent;

    /**
     * Creates new form ReportResponseDialog
     */
    private ReportResponseDialog(@NotNull Path path, @NotNull View parent) {
        super(Main.frame, true);
        this.path = path;
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(Main.frame);
        getRootPane().setBackground(Color.WHITE);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(Option.CANCEL);
            }
        });
    }
    public static void showMessage(@NotNull View parent,@NotNull Path path){
        new ReportResponseDialog(path, parent).setVisible(true);
    }

    private void doClose(Option retStatus) {
        switch (retStatus) {
            case PDF -> SwingUtilities.invokeLater(() -> {
                try {
                    Util.openFile(path.toFile());
                } catch (IOException e) {
                    parent.showError("Ocurrió un error al intentar abrir la carpeta", e);
                }
            });
            case DIR -> SwingUtilities.invokeLater(() -> {
                try {
                    Util.openFile(path.getParent().toFile());
                } catch (IOException e) {
                    parent.showError("Ocurrió un error al intentar abrir la carpeta", e);
                }
            });
            case null, default -> {}
        }
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.nutrehogar.sistemacontable.ui_2.component.Background();
        lblIcon = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnOpenDir = new javax.swing.JButton();
        btnOpenPDF = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setTitle("Reporte generado correctamente");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        background1.setColor1(new java.awt.Color(229, 243, 255));
        background1.setColor2(new java.awt.Color(239, 248, 255));
        background1.setColor3(new java.awt.Color(255, 255, 255));
        background1.setColor4(new java.awt.Color(255, 255, 255));
        background1.setFundType(com.nutrehogar.sistemacontable.ui_2.component.Background.FundType.LINEAL);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(UIManager.getIcon("OptionPane.informationIcon"));
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIcon.setIconTextGap(0);

        lblMessage.setText(LabelBuilder.build("Puede abrir el PDF directamente o verlo en la carpeta de destino"));

        btnOpenDir.setText("Ver carpeta");
        btnOpenDir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDirActionPerformed(evt);
            }
        });

        btnOpenPDF.setText("Ver pdf");
        btnOpenPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPDFActionPerformed(evt);
            }
        });

        btnClose.setText("Cerrar");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(btnOpenDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenDir)
                    .addComponent(btnClose)
                    .addComponent(btnOpenPDF))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnOpenDir);
        getRootPane().setDefaultButton(btnOpenDir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDirActionPerformed
        doClose(Option.DIR);
    }//GEN-LAST:event_btnOpenDirActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        doClose(Option.CANCEL);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(Option.CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btnOpenPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPDFActionPerformed
        doClose(Option.PDF);
    }//GEN-LAST:event_btnOpenPDFActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui_2.component.Background background1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOpenDir;
    private javax.swing.JButton btnOpenPDF;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables

}
