package com.nutrehogar.sistemacontable.ui;

import com.nutrehogar.sistemacontable.ui.crud.AccountSubtypeView;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.nutrehogar.sistemacontable.config.Theme;
import com.nutrehogar.sistemacontable.model.User;
//import com.nutrehogar.sistemacontable.ui.crud.AccountView;
//import com.nutrehogar.sistemacontable.ui.crud.UserView;
import com.nutrehogar.sistemacontable.ui.crud.AccountView;
import com.nutrehogar.sistemacontable.ui.crud.AccountingPeriodView;
import com.nutrehogar.sistemacontable.ui.crud.UserView;
import com.nutrehogar.sistemacontable.ui_2.component.Background;

import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

public class DashboardView extends Background {
    @NotNull
    private User user;
    public DashboardView(@NotNull User adminUser) {
        this.user = adminUser;
        initComponents();
        pnlNav.setVisible(false);
        pnlContent.setOpaque(false);
        buttonPermissionSettings();
        setupViewListeners();
    }

    @Contract(value = "_ -> new", pure = true)
    private @NotNull FlatSVGIcon getIcon(@NotNull String iconName) {
        return new FlatSVGIcon(iconName, Theme.ICON_LG, Theme.ICON_LG);
    }

    public void setUser(@NotNull User user) {
        this.user = user;
        buttonPermissionSettings();
    }

    private void buttonPermissionSettings() {
        if (user.isAdmin()) return;
        btnUser.setVisible(false);
        btnBackup.setEnabled(false);
    }

    public void setupViewListeners() {
        btnAccountSubtype.addActionListener(_ -> setContent(new AccountSubtypeView(user)));
        btnAccount.addActionListener(_ -> setContent(new AccountView(user)));
        btnUser.addActionListener(_ -> setContent(new UserView(user)));
        btnAccountingPeriod.addActionListener(_ -> setContent(new AccountingPeriodView(user)));
        btnHome.addActionListener(_ -> setContent(pnlHome));
    }

    public void setContent(JPanel p) {
        SwingUtilities.invokeLater(() -> {
            if (p != pnlHome) {
                pnlNav.setVisible(true);
            } else {
                pnlNav.setVisible(false);
                btnForm.setBackground(Color.WHITE);
                btnJournal.setBackground(Color.WHITE);
                btnTrialBalance.setBackground(Color.WHITE);
                btnGeneralLedger.setBackground(Color.WHITE);
                btnAccount.setBackground(Color.WHITE);
                btnAccountSubtype.setBackground(Color.WHITE);
            }
            pnlContent.removeAll();
            pnlContent.setLayout(new BorderLayout());
            pnlContent.add(p, BorderLayout.CENTER);
            pnlContent.revalidate();
            pnlContent.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlGroupBtn = new javax.swing.JPanel();
        btnForm = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnAccount = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnTrialBalance = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnAccountSubtype = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnGeneralLedger = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnJournal = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnUser = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnAccountingPeriod = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        pnlNav = new javax.swing.JPanel();
        btnBackup = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnHome = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setColor1(new java.awt.Color(184, 255, 255));
        setColor2(new java.awt.Color(229, 243, 255));
        setColor3(new java.awt.Color(239, 248, 255));
        setColor4(new java.awt.Color(255, 255, 255));
        setNumberOfColors(com.nutrehogar.sistemacontable.ui_2.component.Background.NumberOfColors.FOUR);

        pnlContent.setOpaque(false);

        pnlHome.setOpaque(false);

        pnlGroupBtn.setOpaque(false);

        btnForm.setIcon(getIcon("svgs/form.svg"));
        btnForm.setText("Formulario");

        btnAccount.setIcon(getIcon("svgs/account.svg"));
        btnAccount.setText("Cuentas");

        btnTrialBalance.setIcon(getIcon("svgs/trial_balance.svg"));
        btnTrialBalance.setText("Balance de Comprobación");

        btnAccountSubtype.setIcon(getIcon("svgs/account_subtype.svg"));
        btnAccountSubtype.setText("Subtipos de Cuentas");
        btnAccountSubtype.setToolTipText("");

        btnGeneralLedger.setIcon(getIcon("svgs/general_ledger.svg"));
        btnGeneralLedger.setText("Mayor General");

        btnJournal.setIcon(getIcon("svgs/journal.svg"));
        btnJournal.setText("Libro Diario");

        btnUser.setIcon(getIcon("svgs/user.svg"));
        btnUser.setText("Usuarios");

        btnAccountingPeriod.setIcon(getIcon("svgs/journal2.svg"));
        btnAccountingPeriod.setText("Periodos Contables");

        javax.swing.GroupLayout pnlGroupBtnLayout = new javax.swing.GroupLayout(pnlGroupBtn);
        pnlGroupBtn.setLayout(pnlGroupBtnLayout);
        pnlGroupBtnLayout.setHorizontalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrialBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnForm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccountSubtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGeneralLedger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountingPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlGroupBtnLayout.setVerticalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnForm, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrialBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeneralLedger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccountSubtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(btnAccountingPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNav.setOpaque(false);

        btnBackup.setIcon(getIcon("svgs/backup.svg"));
        btnBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setIcon(new FlatSVGIcon("svgs/home.svg", Theme.ICON_MD, Theme.ICON_MD));
        btnHome.setText("Inicio");
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnAccount;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnAccountSubtype;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnAccountingPeriod;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnBackup;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnForm;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnGeneralLedger;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnHome;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnJournal;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnTrialBalance;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlGroupBtn;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNav;
    // End of variables declaration//GEN-END:variables

}
