package com.nutrehogar.sistemacontable.ui;

import com.nutrehogar.sistemacontable.ui.business.GeneralLedgerView;
import com.nutrehogar.sistemacontable.ui.business.JournalView;
import com.nutrehogar.sistemacontable.ui.business.TrialBalanceView;
import com.nutrehogar.sistemacontable.ui.crud.*;
import com.nutrehogar.sistemacontable.config.Theme;
import com.nutrehogar.sistemacontable.model.User;
import com.nutrehogar.sistemacontable.ui_2.component.Background;

import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;

public class DashboardView extends Background {
    @NotNull
    private User user;
    private AccountingEntryView  accountingEntryView;
    private final CardLayout cardLayout = new CardLayout();
    private final HomeView homeView;
    public DashboardView(@NotNull User adminUser) {
        this.user = adminUser;
        initComponents();
        pnlContent.setLayout(cardLayout);
        pnlNav.setVisible(false);
        this.homeView = new HomeView();
        addView(homeView, "HOME");
        btnHome.addActionListener(_ -> show("HOME"));
    }
    private void addView(@NotNull JPanel panel, @NotNull String name) {
        pnlContent.add(panel, name);
    }
    private void show(@NotNull String name){
        if(name.equals("HOME")){
            pnlNav.setVisible(false);
        }else{
            pnlNav.setVisible(true);
            homeView.resetButtons();
        }
        cardLayout.show(pnlContent, name);
    }
    public void setUser(@NotNull User user) {
        this.user = user;
        buttonPermissionSettings();
        addView(new AccountSubtypeView(user), "SUBTYPE");
        addView(new AccountView(user), "ACCOUNT");
        addView(new UserView(user), "USER");
        this.accountingEntryView = new AccountingEntryView(user);
        addView(accountingEntryView, "ENTRY");
        addView(new AccountingPeriodView(user), "PERIOD");
        addView(new JournalView(user,this::editJournal),"JOURNAL");
        addView(new TrialBalanceView(user,this::editJournal),"TRIAL");
        addView(new GeneralLedgerView(user,this::editJournal),"GENERAL");

        homeView.getBtnForm().addActionListener(_ -> show("ENTRY"));
        homeView.getBtnJournal().addActionListener(_ -> show("JOURNAL"));
        homeView.getBtnTrialBalance().addActionListener(_ -> show("TRIAL"));
        homeView.getBtnGeneralLedger().addActionListener(_ -> show("GENERAL"));
        homeView.getBtnAccountSubtype().addActionListener(_ -> show("SUBTYPE"));
        homeView.getBtnAccount().addActionListener(_ -> show("ACCOUNT"));
        homeView.getBtnUser().addActionListener(_ -> show("USER"));
        homeView.getBtnAccountingPeriod().addActionListener(_ -> show("PERIOD"));

    }
    private void buttonPermissionSettings() {
        if (user.isAdmin()) return;
        homeView.getBtnUser().setVisible(false);
        btnBackup.setEnabled(false);
    }
    private void editJournal(@NotNull Long id){
        accountingEntryView.edit(id);
        show("ENTRY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlNav = new javax.swing.JPanel();
        btnBackup = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();
        btnHome = new com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setColor1(new java.awt.Color(184, 255, 255));
        setColor2(new java.awt.Color(229, 243, 255));
        setColor3(new java.awt.Color(239, 248, 255));
        setColor4(new java.awt.Color(255, 255, 255));
        setNumberOfColors(com.nutrehogar.sistemacontable.ui_2.component.Background.NumberOfColors.FOUR);
        setRadioIncremento(250);

        pnlContent.setOpaque(false);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        pnlNav.setOpaque(false);

        btnBackup.setIcon(Theme.SVGs.BACKUP.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBackup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackup.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setIcon(Theme.SVGs.HOME.getIcon().derive(Theme.ICON_MD, Theme.ICON_MD));
        btnHome.setText("Inicio");
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnBackup;
    private com.nutrehogar.sistemacontable.ui_2.component.DefaultPanelButton btnHome;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlNav;
    // End of variables declaration//GEN-END:variables

}
