/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui;

import com.nutrehogar.sistemacontable.config.Theme;
import lombok.Getter;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Calci
 */
@Getter
public class HomeView extends javax.swing.JPanel {

    private List<JButton> buttons;

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        this.buttons = new ArrayList<>(List.of(btnForm, btnJournal, btnTrialBalance, btnGeneralLedger, btnAccount,btnAccountSubtype,btnUser,btnAccountingPeriod));
    }

    public void resetButtons() {
        for(var b:buttons){
            b.setBackground(Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        pnlGroupBtn = new javax.swing.JPanel();
        btnForm = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnAccount = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnTrialBalance = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnAccountSubtype = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnGeneralLedger = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnJournal = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnUser = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();
        btnAccountingPeriod = new com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton();

        setOpaque(false);

        pnlHome.setOpaque(false);

        pnlGroupBtn.setOpaque(false);

        btnForm.setIcon(UIEntityInfo.ENTRY_FORM.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnForm.setText(UIEntityInfo.ENTRY_FORM.getPlural());

        btnAccount.setIcon(UIEntityInfo.ACCOUNT.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnAccount.setText(UIEntityInfo.ACCOUNT.getPlural());

        btnTrialBalance.setIcon(UIEntityInfo.TRIAL_BALANCE.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnTrialBalance.setText(UIEntityInfo.TRIAL_BALANCE.getPlural());

        btnAccountSubtype.setIcon(UIEntityInfo.ACCOUNT_SUBTYPE.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnAccountSubtype.setText(UIEntityInfo.ACCOUNT_SUBTYPE.getPlural());
        btnAccountSubtype.setToolTipText("");

        btnGeneralLedger.setIcon(UIEntityInfo.GENERAL_LEDGER.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnGeneralLedger.setText(UIEntityInfo.GENERAL_LEDGER.getPlural());

        btnJournal.setIcon(UIEntityInfo.JOURNAL.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnJournal.setText(UIEntityInfo.JOURNAL.getPlural());

        btnUser.setIcon(UIEntityInfo.USER.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnUser.setText(UIEntityInfo.USER.getPlural());

        btnAccountingPeriod.setIcon(UIEntityInfo.ACCOUNTING_PERIOD.getIcon().derive(Theme.ICON_LG, Theme.ICON_LG));
        btnAccountingPeriod.setText(UIEntityInfo.ACCOUNTING_PERIOD.getPlural());

        javax.swing.GroupLayout pnlGroupBtnLayout = new javax.swing.GroupLayout(pnlGroupBtn);
        pnlGroupBtn.setLayout(pnlGroupBtnLayout);
        pnlGroupBtnLayout.setHorizontalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrialBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnForm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccountSubtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGeneralLedger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountingPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlGroupBtnLayout.setVerticalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrialBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeneralLedger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccountSubtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountingPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnAccount;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnAccountSubtype;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnAccountingPeriod;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnForm;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnGeneralLedger;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnJournal;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnTrialBalance;
    private com.nutrehogar.sistemacontable.ui_2.component.HomeViewButton btnUser;
    private javax.swing.JPanel pnlGroupBtn;
    private javax.swing.JPanel pnlHome;
    // End of variables declaration//GEN-END:variables
}
